name: rabbitmq-dotnet-client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-win32:
    name: build/test on windows-latest

    runs-on: windows-latest

    # https://github.com/NuGet/Home/issues/11548
    env:
      NUGET_CERT_REVOCATION_MODE: offline

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Cache installers
        uses: actions/cache@v3
        with:
          # Note: the cache path is relative to the workspace directory
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
          path: ~/installers
          key: ${{ runner.os }}-v0-${{ hashFiles('.ci/versions.json') }}
      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/AppData/Local/NuGet/v3-cache
          key: ${{ runner.os }}-v0-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-v0-nuget-
      - name: Install and start RabbitMQ
        run: ./.ci/install.ps1
      - name: List NuGet sources
        run: dotnet nuget locals all --list
      - name: Restore
        run: dotnet restore ${{ github.workspace }}\Build.csproj --verbosity=normal
      - name: Build
        run: dotnet build ${{ github.workspace }}\Build.csproj --no-restore --verbosity=normal
      - name: Verify
        run: dotnet format ${{ github.workspace }}\RabbitMQDotNetClient.sln --no-restore --verbosity=diagnostic --verify-no-changes
      - name: Test
        run: .\.ci\gha-run-tests.ps1

  build:
    name: build/test on ubuntu-latest

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: pivotalrabbitmq/rabbitmq:master-otp-max
        ports:
         - 5672:5672
         - 15672:15672

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v3-cache
          key: ${{ runner.os }}-v0-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-v0-nuget-
      - name: Restore
        run: dotnet restore ${{ github.workspace }}/Build.csproj --verbosity=normal
      - name: Build
        run: dotnet build ${{ github.workspace }}/Build.csproj --no-restore --verbosity=normal
      - name: Verify
        run: dotnet format ${{ github.workspace }}/RabbitMQDotNetClient.sln --no-restore --verbosity=diagnostic --verify-no-changes
      - name: Test
        run: dotnet test ${{ github.workspace }}/projects/Unit/Unit.csproj --no-restore --no-build --logger "console;verbosity=detailed" --framework "net6.0"
        env:
          RABBITMQ_RABBITMQCTL_PATH: DOCKER:${{job.services.rabbitmq.id}}
